version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
    command: uv run python main.py

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
